language: node_js

sudo: false

node_js:
  - "node"

os:
- linux
- osx

compiler: clang-3.6

env:
  - CXX=clang-3.6

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6

branches:
  only:
    - master
    - /^v.*$/

deploy:
  provider: script
  script: npm run prebuild && npm run prebuild:upload -u ${PREBUILD_UPLOAD}
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
