name: Build/test
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - if: runner.os == 'Linux'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - if: runner.os == 'Linux'
        run: npm run-script test-compare
  test_windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run-script test-windows
