name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Set up examples
        run: |
          git clone https://github.com/ruby/spec examples/ruby_spec --single-branch --depth=1 --filter=blob:none
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: ${{runner.os == 'Linux'}}
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |
            examples/*.rb
            !examples/ruby_spec/command_line/fixtures/bad_syntax.rb
            !examples/ruby_spec/command_line/fixtures/freeze_flag_required_diff_enc.rb
            !examples/ruby_spec/core/enumerable/shared/inject.rb
            !examples/ruby_spec/language/fixtures/freeze_magic_comment_required_diff_enc.rb
            !examples/ruby_spec/language/string_spec.rb
            !examples/ruby_spec/core/proc/ruby2_keywords_spec.rb
            !examples/ruby_spec/language/fixtures/utf16-be-nobom.rb
            !examples/ruby_spec/language/fixtures/utf16-le-nobom.rb
            !examples/ruby_spec/language/lambda_spec.rb
